project:
  type: website
  output-dir: _site

website:
  title: "Anna og Sebastian's Bryllup"
  site-url: https://tillykkemeddagen.com   # change later to your real domain
  navbar:
    left:
      - text: "Menu"
        href: index.qmd#about
      - text: "Ønskeliste"
        href: index.qmd#mypub
      - text: "Toast master"
        href: index.qmd#contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
